[package]
name = "tps"
version = "0.1.0"
authors = ["Rishi Desai <desai.rishi1@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
crossbeam = "0.7"